const english = {
    'Ruang keuangan Anda': 'Your financial space', 'Keuangan pribadi': 'Personal finance', 'Profil Kekayaan Awal': 'Initial Wealth Profile', 'Dashboard': 'Dashboard', 'Profile': 'Profile', 'Ubah password': 'Change password', 'Password saat ini': 'Current password', 'Password baru': 'New password', 'Konfirmasi password baru': 'Confirm new password', 'Simpan password': 'Save password', 'Ringkasan keuangan': 'Financial summary', 'Perjalanan finansial Anda': 'Your financial journey', 'Selangkah lebih terencana': 'One step more intentional', 'Lengkapi profil kekayaan': 'Complete wealth profile', 'Total aset': 'Total assets', 'Total kewajiban': 'Total liabilities', 'Kekayaan bersih': 'Net worth', 'Kemampuan menabung': 'Savings capacity', 'Mulai dari sini': 'Start here', 'Catat kekayaan awal': 'Record your initial wealth', 'Susun anggaran': 'Create a budget', 'Aktivitas keuangan': 'Financial activity', 'Profil Kemampuan Menabung': 'Savings Capacity Profile', 'Cek Kesehatan Finansial': 'Financial Health Check', 'Level Kekayaan': 'Wealth Level', 'Saran Budgeting': 'Budgeting Suggestions', 'Atur Budgeting': 'Budgeting', 'Mutasi Rekening': 'Account Transactions', 'Pindah Kas/ Tabung': 'Transfer Cash / Savings', 'Pendapatan': 'Income', 'Pengeluaran': 'Expenses', 'Utang': 'Debt', 'Piutang': 'Receivables', 'Beli Jual Barang': 'Buy & Sell Items', 'Investasi': 'Investments', 'Keluar': 'Logout', 'Akun': 'Account', 'Tambah': 'Add', 'Ubah': 'Edit', 'Hapus': 'Delete', 'Batal': 'Cancel', 'Simpan': 'Save', 'Belum ada data.': 'No data yet.', 'Data profil kekayaan tidak dapat dimuat.': 'Initial wealth data could not be loaded.', 'PREFERENSI AKUN': 'ACCOUNT PREFERENCES', 'Atur bahasa dan mata uang agar ringkasan keuangan terasa lebih personal.': 'Set your language and currency to make your financial summary feel more personal.', 'Pilih Bahasa Indonesia atau English untuk tampilan aplikasi.': 'Choose Bahasa Indonesia or English for the application interface.', 'Bahasa tampilan': 'Display language', 'Mata uang': 'Currency', 'Simpan pengaturan': 'Save settings',
    'Dooeed Admin': 'Dooeed Admin', 'Monitoring user': 'User monitoring', 'Nama / email': 'Name / email', 'Cari user': 'Search users', 'Status': 'Status', 'Semua': 'All', 'Urutkan': 'Sort by', 'Nama': 'Name', 'Total akun': 'Total accounts', 'Total transaksi': 'Total transactions', 'Arah': 'Direction', 'Menurun': 'Descending', 'Menaik': 'Ascending', 'Cari': 'Search', 'Memuat data…': 'Loading data…', 'Coba lagi': 'Try again', 'Dashboard': 'Dashboard', 'Riwayat tindakan': 'Action history', 'Terdaftar': 'Registered', 'Tindakan admin': 'Admin actions', '20 transaksi terakhir': '20 latest transactions', 'Tanggal': 'Date', 'Akun': 'Account', 'Jenis': 'Type', 'Jumlah': 'Amount', 'Deskripsi': 'Description', 'Alasan': 'Reason', 'Batal': 'Cancel', 'Konfirmasi': 'Confirm', 'Tutup': 'Close', 'Accounts & current balance': 'Accounts & current balance', 'Outstanding debts': 'Outstanding debts', 'Utang berstatus active / overdue. Mata uang utang belum tersedia pada data aplikasi.': 'Debts with active or overdue status. Debt currency is not available in the application data.', 'Ringkasan akun dan jumlah aset; valuasi pasar belum tersedia.': 'Account and asset-count summary; market valuation is not available.', 'Belum ada akun.': 'No accounts yet.', 'Suspend': 'Suspend', 'Activate': 'Activate', 'Reset Password': 'Reset Password', 'Password dan token lama langsung dibatalkan. Link reset dikirim ke email user.': 'The previous password and tokens are immediately revoked. A reset link is sent to the user email.', 'User disembunyikan dari daftar; data keuangan dan audit tetap tersimpan.': 'The user is hidden from the list; financial and audit data remain stored.', 'Tindakan gagal. Silakan coba lagi.': 'Action failed. Please try again.', 'Filter': 'Filter', 'Reset': 'Reset', 'Admin ID': 'Admin ID', 'User ID': 'User ID', 'UUID admin': 'Admin UUID', 'UUID user': 'User UUID', 'Timestamp': 'Timestamp', 'Admin': 'Admin', 'User': 'User', 'Action': 'Action', 'Reason': 'Reason',
    'Rencana Nabung Setiap Bulan': 'Monthly Savings Plan', 'Dana Darurat': 'Emergency Fund', 'Dana Pensiun': 'Retirement Fund', 'Pemasukan Bulanan (Average)': 'Monthly Income (Average)', 'Pengeluaran Bulanan (Average)': 'Monthly Expenses (Average)', 'Kemampuan Menabung (Average)': 'Savings Capacity (Average)', 'Tanggal Lahir': 'Date of Birth', 'Usia Hari ini': 'Current Age', 'Usia Pensiun': 'Retirement Age', 'Usia Memberi Warisan': 'Inheritance Age', 'Sisa waktu sebelum pensiun (tahun)': 'Time until retirement (years)', 'Dana yang dibutuhkan sebelum pensiun': 'Funds needed before retirement', 'Durasi pensiun (tahun)': 'Retirement duration (years)', 'Dana yang dibutuhkan saat pensiun': 'Funds needed during retirement', 'Rata-rata pemasukan selama 12 bulan terakhir.': 'Average income over the last 12 months.', 'Tidak termasuk cicilan utang, investasi, dan pembelian mewah.': 'Excludes debt installments, investments, and luxury purchases.', 'Batas atas kemampuan menabung setiap bulan.': 'The upper limit of monthly savings capacity.', 'Pengeluaran bulanan × 12 × sisa waktu sebelum pensiun.': 'Monthly expenses × 12 × time until retirement.', 'Pengeluaran bulanan × 12 × durasi pensiun.': 'Monthly expenses × 12 × retirement duration.', 'Perbarui data ini secara berkala agar rencana keuangan tetap relevan.': 'Update this information periodically to keep your financial plan relevant.', 'Profil berhasil disimpan.': 'Profile saved successfully.', 'Simpan profil': 'Save profile',
    'Kas': 'Cash', 'Aset Setara Kas': 'Cash Equivalents', 'Aset Tidak Lancar': 'Non-current Assets', 'Kekayaan bersih awal': 'Initial net worth', 'Nama Rekening': 'Account name', 'Saldo': 'Balance', 'Nama Aset': 'Asset name', 'Nilai Beli': 'Purchase value', 'Peminjam': 'Borrower', 'Nominal': 'Amount', 'Pemberi Utang': 'Lender', 'Jenis Utang': 'Debt type', 'Selain kartu kredit & paylater': 'Other than credit cards & pay-later', 'Kartu kredit & paylater': 'Credit cards & pay-later', 'Selain Kartu Kredit & Paylater': 'Other than Credit Cards & Pay-later', 'Total:': 'Total:', 'Data gagal disimpan.': 'Failed to save data.', 'Hapus data ini?': 'Delete this entry?',
    'Daftar User': 'User List', 'Audit Log': 'Audit Log', 'Cari nama atau email': 'Search name or email', 'Urutkan': 'Sort by', 'Terapkan': 'Apply', 'Tidak ada data ditemukan.': 'No data found.', 'Sebelumnya': 'Previous', 'Berikutnya': 'Next', 'Halaman': 'Page', 'data': 'records', 'Akses ditolak.': 'Access denied.', 'Data gagal dimuat. Silakan coba lagi.': 'Data could not be loaded. Please try again.', 'User tidak ditemukan.': 'User not found.', 'Belum ada transaksi.': 'No transactions yet.', 'Belum ada saldo.': 'No balances yet.', 'Belum ada investasi.': 'No investments yet.', 'akun': 'accounts', 'Terdaftar': 'Registered', 'Ubah role': 'Change role', 'Hapus user': 'Delete user', 'Alasan (wajib)': 'Reason (required)', 'Alasan (opsional)': 'Reason (optional)',
};

export function translate(value, locale = document.documentElement.lang) {
    return locale === 'en' ? (english[value] ?? value) : value;
}

export function applyLocale(locale) {
    document.documentElement.lang = locale;
    if (locale !== 'en') return;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
        const value = node.nodeValue.trim();
        if (english[value]) node.nodeValue = node.nodeValue.replace(value, translate(value, locale));
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
        if (english[element.placeholder]) element.placeholder = translate(element.placeholder, locale);
    });
}
